### ISSUE TITLE
Native lib not loading on macos

### ISSUE THREAD

**Issue by elmart-devo** [gliwka/hyperscan-java#114]
Running `mvn verify` on macos produces the following:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.gliwka.hyperscan.wrapper.DeallocationTest
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.18 s <<< FAILURE! - in com.gliwka.hyperscan.wrapper.DeallocationTest
[ERROR] scrannerShouldThrowExceptionOnCallingSizeAfterClose  Time elapsed: 0.17 s  <<< ERROR!
java.lang.UnsatisfiedLinkError: no jnihyperscan in java.library.path
	at com.gliwka.hyperscan.wrapper.DeallocationTest.scrannerShouldThrowExceptionOnCallingSizeAfterClose(DeallocationTest.java:32)
Caused by: java.lang.UnsatisfiedLinkError: no hs_runtime in java.library.path
	at com.gliwka.hyperscan.wrapper.DeallocationTest.scrannerShouldThrowExceptionOnCallingSizeAfterClose(DeallocationTest.java:32)

[ERROR] databaseShouldThrowExceptionOnCallingSizeAfterClose  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.gliwka.hyperscan.jni.hs_compile_error_t
	at com.gliwka.hyperscan.wrapper.DeallocationTest.databaseShouldThrowExceptionOnCallingSizeAfterClose(DeallocationTest.java:16)
```

This is, dynamic lib is not being found on macos.

After some investigation, it turns out the problem comes from the maven plugin used to normalize platform classifier on companion project `hyperscan-java-native`. Such plugin (os-maven-plugin) uses `osx` for macos, where JavaCPP loader expects `macosx`. This is, dynamic lib is placed in a java package including `osx`, while JavaCPP loader looks for it in a package named `macosx`, and the loading fails. JavaCPP also expects the name of the platform dependent artifact to also use `macosx` instead of `osx`.

So, to fix this, changes are needed in both `hyperscan-java` and `hyperscan-java-native`. Will be sending PR's for that.

**Comment by elmart-devo** [comment]
As to why this wasn't detected here, it seems there's a matrix config in github workflow, but currently it's running only on ubuntu.
