### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jnihyperscan in java.library.path

### ISSUE THREAD

**Issue by johnwyz88** [gliwka/hyperscan-java#124]
After pulling the latest version from maven, I start getting this error
```
simpleSingleExpression{SerializeDatabase}[1]  Time elapsed: 0.013 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: no jnihyperscan in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1718)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1328)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1132)
	at com.gliwka.hyperscan.jni.JavaCppPreset.<clinit>(JavaCppPreset.java:49)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1200)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1132)
	at com.gliwka.hyperscan.jni.hs_expr_info_t.<clinit>(hs_expr_info_t.java:20)
	at com.gliwka.hyperscan.wrapper.Expression.validate(Expression.java:71)
	at com.gliwka.hyperscan.wrapper.IntegrationTest.simpleSingleExpression(IntegrationTest.java:20)
```

Full logs: https://justpaste.it/37dzy

**Comment by gliwka** [comment]
Which OS? Are you trying to build it yourself?

**Comment by johnwyz88** [comment]
Linux. I have some custom modification on top so I need to build the source.

**Comment by johnwyz88** [comment]
Do you have a build script that I can reference?

**Comment by gliwka** [comment]
A regular maven build should do the trick for the java part.

It seems the tests in your build fail, because it can't find the hyperscan binaries. Those are provided in a seperate dependency.

Do you have the following dependencies in the build of your fork? 

https://github.com/gliwka/hyperscan-java/blob/27dc576faf984160686a6a0a0b128ba97682ab2a/pom.xml#L191:L206

**Comment by johnwyz88** [comment]
I see. Thanks!

**Comment by gliwka** [comment]
PS: If your custom modifications are general enough and useful to others, we could also include them in this repo.
