### ISSUE TITLE
NullPointerException: null

### ISSUE THREAD

**Issue by jiabochao** [gliwka/hyperscan-java#166]
```
java.lang.NullPointerException: null
	at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:897) ~[na:na]
	at java.base/java.lang.Iterable.forEach(Iterable.java:74) ~[na:na]
	at com.gliwka.hyperscan.wrapper.Scanner.processMatches(Scanner.java:157) ~[hyperscan-5.4.0-2.0.0.jar:na]
	at com.gliwka.hyperscan.wrapper.Scanner.scan(Scanner.java:146) ~[hyperscan-5.4.0-2.0.0.jar:na]
[thread 3032 also had an error]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363) at pc=0x00007ffa5c9b466c, pid=7300, tid=29304
#
# JRE version: OpenJDK Runtime Environment Temurin-11.0.13+8 (11.0.13+8) (build 11.0.13+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (11.0.13+8, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  [KERNELBASE.dll+0x4466c]Error getting method ID of java/lang/RuntimeException/<init>Error getting method ID of java/lang/RuntimeException/<init>

Error getting method ID of java/lang/RuntimeException/<init>
Error getting method ID of java/lang/RuntimeException/<init>
Error getting method ID of java/lang/RuntimeException/<init>
Error getting method ID of java/lang/RuntimeException/<init>
Error getting method ID of java/lang/RuntimeException/<init>
Error getting method ID of java/lang/RuntimeException/<init>
Error getting method ID of java/lang/RuntimeException/<init>
Error getting method ID of java/lang/RuntimeException/<init>
Error getting method ID of java/lang/RuntimeException/<init>
Error getting method ID of java/lang/RuntimeException/<init>

#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\jiabo\Projects\IdeaProjects\OSS\logs-shipper\hs_err_pid7300.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by gliwka** [comment]
Can you please provide a minimal reproduction case or code to reproduce this issue?
