### ISSUE TITLE
Concurrency and blocking with many threads

### ISSUE THREAD

**Issue by rbjarnason** [gliwka/hyperscan-java#89]
Thanks for an excellent wrapper, we're using Hyperscan to search CommonCrawl using large EC2 instances. But we've run into a problem with concurrency where the CPUs are not used unless 15%-20% and the threads are blocked a lot of the time.

The blocking is happening on WeakHashMap, StandardCharsets, and SynchronizedMap as shown below. Any ideas or leads?

"pool-2-thread-29" #58 prio=5 os_prio=0 cpu=37128.32ms elapsed=220.66s tid=0x00007fe8a05e6970 nid=0xac08 waiting for monitor entry  [0x00007fcde49ac000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.util.Collections$SynchronizedMap.get(java.base@15.0.2/Collections.java:2634)
	- waiting to lock <0x00007fcf8b5b11d8> (a java.util.Collections$SynchronizedMap)
	at com.sun.jna.Native.getLibraryOptions(Native.java:730)
	at com.sun.jna.CallbackReference.getFunctionPointer(CallbackReference.java:438)
	at com.gliwka.hyperscan.jna.HyperscanLibraryDirect.hs_scan(Native Method)
	at com.gliwka.hyperscan.wrapper.Scanner.scan(Scanner.java:98)
	at org.cf.acks.WetArchiveProcessor.processLineForKeywords(WetArchiveProcessor.java:196)
	at org.cf.acks.WetArchiveProcessor.run(WetArchiveProcessor.java:137)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@15.0.2/Executors.java:515)
	at java.util.concurrent.FutureTask.run(java.base@15.0.2/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@15.0.2/ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@15.0.2/ThreadPoolExecutor.java:630)
	at java.lang.Thread.run(java.base@15.0.2/Thread.java:832)

 Here is our open source project: https://github.com/CitizensFoundation/ac-keyword-scanner

**Comment by rbjarnason** [comment]
I decided to spawn one java process per CPU instead, and fixed some unrelated IO issues and now I'm scanning with all CPUs constantly at 92-95% on a c5n.18xlarge EC2 instance with 72 CPUs. This allows us to scan a whole month of CommonCrawl, 72,000 files, 9.2 TB of gzipped text with hundreds of keywords in about 4 hours.

**Comment by gliwka** [comment]
Thank you for the bug report and follow-up!

I'll be releasing a new version based on 5.4 and generated JNI code instead of JNA by the end of this week, which will remove the lock contention.

I will give you a ping here once it is released.

**Comment by gliwka** [comment]
The new implementation based on JNI and hyperscan 5.4.0 has landed on develop. Feel free to give it a try.

Release to maven central will follow soon, need to migrate the build to GitHub first.

**Comment by johnwyz88** [comment]
Hi, we are using Maven 1.0.0 and still getting this bug. Could you release the fix to Maven?

**Comment by gliwka** [comment]
Version 5.4.0-2.0.0 with the fix has been released and should be in maven central in a couple minutes.
